FROM almalinux:9
RUN mkdir /tmp/pushpa-dir
WORKDIR /tmp/pushpa-dir                    #RUN cd/tmp/pushpa-dir # cd will not work on docker
RUN pwd
RUN echo "Hello Pushpa" >hello.txt
CMD ["sleep" , "200"]